blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # http://localhost:8000/blog/1
    path('', views.blog_list, name="blog_list"),
    path('<int:blog_pk>', views.blog_detail, name="blog_detail"),
    path('type/<int:blog_type_pk>', views.blogs_with_type, name="blogs_with_type"),
    path('date/<int:year>/<int:month>', views.blogs_with_date, name="blogs_with_date"),
]

user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # http://localhost:8000/blog/1
    path('login/', views.login, name='login'),
    path('login_for_medal/', views.login_for_medal, name='login_for_medal'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('user_info/', views.user_info, name='user_info'),
    path('change_nickname/', views.change_nickname, name='change_nickname'),
    path('bind_email/', views.bind_email, name='bind_email'),
    path('send_verification_code/', views.send_verification_code, name='send_verification_code'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User


# 自定义的用户模型
class Profile(models.Model):
    # 与Django自带user模型相关联
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='昵称')
    nickname = models.CharField(max_length=20, default='')

    def __str__(self):
        return '<Profile: %s for %s>' % (self.nickname, self.user.username)


def get_nickname(self):
    if Profile.objects.filter(user=self).exists():
        profile = Profile.objects.get(user=self)
        return profile.nickname
    else:
        return ''


def get_nickname_or_username(self):
    if Profile.objects.filter(user=self).exists():
        profile = Profile.objects.get(user=self)
        return profile.nickname
    else:
        return self.username


def has_nickname(self):
    return Profile.objects.filter(user=self).exists()


User.get_nickname = get_nickname
User.get_nickname_or_username = get_nickname_or_username
User.has_nickname = has_nickname

user/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.models import User


# 用户登陆的表单
class LoginForm(forms.Form):
    username = forms.CharField(label='用户名',
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入用户名'}))
    password = forms.CharField(label='密码',
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '请输入密码'}))

    # 验证用户信息
    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        user = auth.authenticate(username=username, password=password)
        if user is None:
            raise forms.ValidationError('用户名或密码不正确')
        else:
            self.cleaned_data['user'] = user
        return self.cleaned_data


# 用户注册的表单
class RegForm(forms.Form):
    username = forms.CharField(label='用户名',
                               max_length=20,
                               min_length=3,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入3-20位用户名'}))
    email = forms.EmailField(label='邮箱',
                             widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': '请输入邮箱'}))
    password = forms.CharField(label='密码',
                               min_length=6,
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '请输入密码'}))
    password_again = forms.CharField(label='再输入一次密码',
                                     min_length=6,
                                     widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '请再一次输入密码'}))

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('用户名已存在')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('邮箱已存在')
        return email

    # 检查密码是否一致，注意函数名
    def clean_password_again(self):
        password = self.cleaned_data['password']
        password_again = self.cleaned_data['password_again']
        if password != password_again:
            raise forms.ValidationError('两次输入的密码不一致')
        return password


# 修改昵称的表单
class ChangeNicknameForm(forms.Form):
    nickname_new = forms.CharField(
        label='新的昵称',
        max_length=20,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': '请输入新的昵称'}
        )
    )

    def __init__(self, *args, **kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user')
        super(ChangeNicknameForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 判断用户是否登陆
        if self.user.is_authenticated:
            self.cleaned_data['user'] = self.user
        else:
            raise forms.ValidationError('用户尚未登陆')
        return self.cleaned_data

    def clean_nickname_new(self):
        # 消除空格
        nickname_new = self.cleaned_data.get('nickname_new', '').strip()
        if nickname_new == '':
            raise ValueError('新的昵称不能为空')
        return nickname_new


# 绑定邮箱
class BindEmailForm(forms.Form):
    email = forms.EmailField(
        label='邮箱',
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': '请输入正确的邮箱'}
        )
    )
    verification_code = forms.CharField(
        label='验证码',
        required=False,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': '点击"发送验证码"将验证码发送到邮箱'}
        )
    )

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(BindEmailForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 判断用户是否登陆
        if self.request.user.is_authenticated:
            self.cleaned_data['user'] = self.request.user
        else:
            raise forms.ValidationError('用户尚未登陆')
        # 判断用户是否已经绑定邮箱
        if self.request.user.email != '':
            raise forms.ValidationError('你已经绑定邮箱了')
        # 判断验证码
        code = self.request.session.get('bind_email_code', '')
        ver_code = self.cleaned_data.get('verification_code', '')
        if not (code != '' and code == ver_code):
            raise forms.ValidationError('验证码不正确')
        return self.cleaned_data

    # 检查邮箱是否被绑定
    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('该邮箱已被绑定')
        return email

    # 检查验证码是否存在
    def clean_verification_code(self):
        verification_code = self.cleaned_data.get('verification_code', '').strip()
        if verification_code == '':
            raise forms.ValidationError('验证码不能为空')
        return verification_code

user/views.py
# -*- coding:utf-8 -*-
import datetime
import string
import random
import time
from django.shortcuts import render, redirect
from django.contrib.contenttypes.models import ContentType
from django.db.models import Sum
from django.http import JsonResponse
from django.contrib import auth
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.urls import reverse
from .forms import LoginForm, RegForm, ChangeNicknameForm, BindEmailForm
from .models import Profile


# 用户登录
def login(request):
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            user = login_form.cleaned_data['user']
            auth.login(request, user)
            # 用户成功登陆则重定向到之前的地址
            return redirect(request.GET.get('from', reverse('home')))
    else:
        login_form = LoginForm()

    context = {}
    context['login_form'] = login_form
    return render(request, 'user/login.html', context)


# 用户表单登录
def login_for_medal(request):
    login_form = LoginForm(request.POST)
    data = {}
    if login_form.is_valid():
        user = login_form.cleaned_data['user']
        auth.login(request, user)
        data['status'] = 'SUCCESS'
    else:
        data['status'] = 'ERROR'
    # 直接返回data无法解析
    return JsonResponse(data)


# 注册
def register(request):
    if request.method == 'POST':
        reg_form = RegForm(request.POST)
        if reg_form.is_valid():
            username = reg_form.cleaned_data['username']
            password = reg_form.cleaned_data['password']
            email = reg_form.cleaned_data['email']
            # 创建用户
            user = User.objects.create_user(username, email, password)
            user.save()
            # 登陆用户
            user = auth.authenticate(username=username, password=password)
            auth.login(request, user)
            return redirect(request.GET.get('from', reverse('home')))
    else:
        reg_form = RegForm()
    context = {}
    context['reg_form'] = reg_form
    return render(request, 'user/register.html', context)


# 用户登出
def logout(request):
    auth.logout(request)
    # 返回当前页面
    return redirect(request.GET.get('from', reverse('home')))


# 用户信息
def user_info(request):
    context = {}
    return render(request, 'user/user_info.html', context)


# 修改昵称
def change_nickname(request):
    redirect_to = request.GET.get('from', reverse('home'))
    if request.method == 'POST':
        form = ChangeNicknameForm(request.POST, user=request.user)
        if form.is_valid():
            nickname_new = form.cleaned_data['nickname_new']
            profile, created = Profile.objects.get_or_create(user=request.user)
            profile.nickname = nickname_new
            profile.save()
            return redirect(redirect_to)
    else:
        form = ChangeNicknameForm()
    context = {}
    context['page_title'] = '修改昵称'
    context['form_title'] = '修改昵称'
    context['submit_text'] = '修改'
    context['form'] = form
    # 返回url
    context['return_back_url'] = redirect_to
    return render(request, 'form.html', context)


# 绑定邮箱
def bind_email(request):
    redirect_to = request.GET.get('from', reverse('home'))
    if request.method == 'POST':
        form = BindEmailForm(request.POST, request=request)
        if form.is_valid():
            email = form.cleaned_data['email']
            request.user.email = email
            request.user.save()
            return redirect(redirect_to)
    else:
        form = BindEmailForm()
    context = {}
    context['page_title'] = '绑定邮箱'
    context['form_title'] = '绑定邮箱'
    context['submit_text'] = '绑定'
    context['form'] = form
    # 返回url
    context['return_back_url'] = redirect_to
    return render(request, 'user/bind_email.html', context)


# 发送验证码
def send_verification_code(request):
    data = {}
    email = request.GET.get('email', '')
    if email != '':
        # 生成验证码
        code = ''.join(random.sample(string.ascii_letters + string.digits, 4))
        # 根据时间判断是否发送邮件
        now_time = int(time.time())
        send_code_time = request.session.get('send_code_time', 0)
        if now_time-send_code_time < 30:
            data['status'] = 'ERROR'
        else:
            # 发送邮件
            request.session['bind_email_code'] = code
            request.session['send_code_time'] = send_code_time
            send_mail(
                '绑定邮箱',
                '验证码: %s' % code,
                'hanjiangong.swust@qq.com',
                [email],
                fail_silently=False,
            )
            data['status'] = 'SUCCESS'
    else:
        data['status'] = 'ERROR'
    return JsonResponse(data)

user/templates/user/bind_email.html
{% extends 'form.html' %}

{% block other_buttons %}
    <button id="send_code" class="btn btn-primary">发送验证码</button>
{% endblock %}

{% block script_extends %}
    <script type="text/javascript">
        $("#send_code").click(function () {
            var email = $("#id_email").val();
            if(email==""){
                $("#tip").text('* 邮箱不能为空');
                return false;
            }

            {# 异步发送验证码 #}
            $.ajax({
                url: "{% url 'send_verification_code' %}",
                type: "GET",
                data:{
                    'email': email
                },
                cache: false,
                success:function (data) {
                    if(data['status'] == 'ERROR'){
                        alert(data['status']);
                    }
                },
            });
            {# 按钮不可点 #}
            $(this).addClass('disabled');
            $(this).attr('disabled', true);
            var time = 30;
            $(this).text(time + 's');
            var interval = setInterval(() => {
                if(time <= 0){
                    clearInterval(interval);
                    $(this).removeClass('disabled');
                    $(this).attr('disabled', false);
                    $(this).text('发送验证码');
                    return false;
                }
                time -- ;
                $(this).text(time + 's');
            }, 1000);
        });
    </script>
{% endblock %}

user/templates/user/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}我的网站|登陆{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                {# 未登录跳转到登录页面 #}
                {% if not user.is_authenticated %}
                    <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">登陆</h3>
                    </div>
                    <div class="panel-body">
                        {# 因为登陆后指向的还是本地址，故action='{% url 'login' %}'可用#代替 #}
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% for field in login_form %}
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                                <p class="text-danger">{{ field.errors.as_text }}</p>
                            {% endfor %}
                            <span class="pull-left text-danger ">{{ login_form.non_field_errors }}</span>

                            <input type="submit" value="登陆" class="btn btn-primary pull-right">
                        </form>
                    </div>
                </div>
                {% else %}
                    <script type="text/javascript">
                        window.location.href = '/';
                    </script>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

user/templates/user/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}我的网站|用户注册{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                {% if not user.is_authenticated %}
                    <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">用户注册</h3>
                    </div>
                    <div class="panel-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% for field in reg_form %}
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                                <p class="text-danger">{{ field.errors.as_text }}</p>
                            {% endfor %}
                            <span class="pull-left text-danger ">{{ reg_form.non_field_errors }}</span>

                            <input type="submit" value="注册" class="btn btn-primary pull-right">
                        </form>
                    </div>
                </div>
                {% else %}
                    <script type="text/javascript">
                        window.location.href = '/';
                    </script>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

user/templates/user/user_info.html
{% extends 'base.html' %}

{% block title %}个人资料{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                {% if user.is_authenticated %}
                    <h2>{{ user.username }}</h2>
                    <ul>
                        <li>昵称：{{ user.get_nickname }}
                            <a href="{% url 'change_nickname' %}?from={{ request.get_full_path }}">修改昵称</a></li>
                        <li>邮箱：
                            {% if user.email %}
                                {{ user.email }}
                            {% else %}
                                未绑定 <a href="{% url 'bind_email' %}?from={{ request.get_full_path }}"> 绑定邮箱</a>
                            {% endif %}
                        </li>
                        <li>
                            上一次登录时间：{{ user.last_login|date:"Y-m-d H:i:s" }}
                        </li>
                        <li><a href="#">修改密码</a></li>
                    </ul>
                {% else %}
                    <script type="text/javascript">
                        window.location.href = '/';
                    </script>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}